apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-deployment
  labels:
    app: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata: 
      labels:
        app: accounts
    spec: 
      containers:
        - name: accounts
          image: miguelmazo/accounts
          ports:
          - containerPort: 8080
          env:
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: SPRING_PROFILES_ACTIVE
          - name: SPRING_CONFIG_IMPORT
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: SPRING_CONFIG_IMPORT
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE